/**
 * АНГЛІЙСЬКИЙ СЛОВНИК — ГЕНЕРОВАНИЙ ФАЙЛ, руками не правити.
 *
 * Ключ — український рядок із виклику `tr()`/`tx()`; значення — переклад.
 * ДЖЕРЕЛО — `scripts/i18n/dict.json`; збирає `scripts/i18n/gen-dict.js`:
 *
 *     node scripts/i18n/gen-dict.js scripts/i18n/dict.json
 *
 * Джерело — памʼять перекладів, тож воно може містити БІЛЬШЕ за цей файл:
 * генератор виписує лише ключі, які СПРАВДІ Є В КОДІ, тож ключ, що осиротів
 * після рефакторингу, зникає звідси сам, а переклад лишається на випадок,
 * коли рядок повернеться. Гард `tests/unit/i18n.test.ts` падає, щойно код
 * і словник розійдуться в будь-який бік, і окремо — щойно цей файл виявиться
 * ПРАВЛЕНИМ РУКАМИ, тобто не збігається з тим, що дає генератор.
 *
 * ГЛОСАРІЙ (терміни, що мусять читатись однаково по всьому застосунку):
 *   обʼєкт → unit            база → database        підбірка → collection
 *   Вільно → Vacant          Зайнято → Occupied     Продаж → For sale
 *   орендар → tenant         орендодавець → landlord
 *   договір → lease          експлуатаційні → service charges
 *   корисна площа → usable area   розрахункова площа → billable area
 *
 * «Вільно» — саме `Vacant`, а не `Free`: англійською `free` читається
 * як «безкоштовно», тобто статус обʼєкта перетворився б на обіцянку ціни.
 *
 * Завантажується ДИНАМІЧНО (`await import`) і лише для англійської — щоб
 * український користувач, якого більшість, не платив за цей файл на
 * холодному старті. Те саме правило, що для `xlsx` і `jsPDF`.
 */
export const EN: Record<string, string> = {
  " · {0} поверх": " · floor {0}",
  " та ще {0}": " and {0} more",
  "-1, 2, підвал": "-1, 2, basement",
  "— не імпортувати —": "— do not import —",
  "…і ще {0}": "…and {0} more",
  "· отримано": "· received",
  "«{0}» — формат не підтримується (тільки PDF, DOC, DOCX)": "“{0}” — unsupported format (PDF, DOC, DOCX only)",
  "«{0}» буде видалено назавжди.": "“{0}” will be deleted permanently.",
  "«{0}» вже існує або вжито двічі": "“{0}” already exists or is used twice",
  "«{0}» вже існує в цій базі": "“{0}” already exists in this database",
  "«{0}» втратить право редагувати базу.": "“{0}” will lose the right to edit this database.",
  "«{0}» перевищує 20 МБ": "“{0}” exceeds 20 MB",
  "[notifications] realtime-канал відпав:": "[notifications] realtime channel dropped:",
  "{0} (копія {1})": "{0} (copy {1})",
  "{0} (копія)": "{0} (copy)",
  "{0} {1} бази": "{0} {1} in the database",
  "{0} {1} без папки": "{0} {1} with no folder",
  "{0} {1} буде видалено назавжди — повернути їх неможливо.": "{0} {1} will be deleted permanently — this cannot be undone.",
  "{0} {1} буде переміщено": "{0} {1} will be moved",
  "{0} {1} залишаться в базі, але без папки.": "{0} {1} will stay in the database but without a folder.",
  "{0} {1} переміщено": "{0} {1} moved",
  "{0} {1} у базі «{2}»": "{0} {1} in “{2}”",
  "{0} {1}/{2}": "{0} {1}/{2}",
  "{0} вільних": "{0} vacant",
  "{0} год тому": "{0} h ago",
  "{0} дн.": "{0} d",
  "{0} дні тому": "{0} days ago",
  "{0} днів тому": "{0} days ago",
  "{0} з {1} фото": "{0} of {1} photos",
  "{0} м²": "{0} m²",
  "{0} обʼєктів": "{0} units",
  "{0} платежів · {1} міс.": "{0} payments · {1} mo",
  "{0} пов.": "fl. {0}",
  "{0} поверх": "floor {0}",
  "{0} успішно, {1} з помилкою": "{0} succeeded, {1} failed",
  "{0} фото завантажено": "{0} photos uploaded",
  "{0} фото збережено": "{0} photos saved",
  "{0} хв тому": "{0} min ago",
  "{0}: площа — лише число": "{0}: area must be a number",
  "{0}{1}": "{0}{1}",
  "{0}/добу": "{0}/day",
  "{0}/м²/міс": "{0}/m²/mo",
  "{0}% · {1} на продаж": "{0}% · {1} for sale",
  "{0}% заповнено": "{0}% occupied",
  "/добу": "/day",
  "/м²": "/m²",
  "/міс": "/mo",
  "0 об.": "0 un.",
  "1 обʼєкт буде видалено": "1 unit will be deleted",
  "1, 2, B-1, МП": "1, 2, B-1, PS",
  "1. Назви базу": "1. Name the database",
  "1. Що це за сервіс": "1. What this service is",
  "1. Які дані ми отримуємо": "1. What data we receive",
  "10. Контакти": "10. Contacts",
  "2. Ваш акаунт": "2. Your account",
  "2. Додай обʼєкти": "2. Add units",
  "2. Навіщо ми це обробляємо": "2. Why we process it",
  "3. Ваш контент і ваша відповідальність": "3. Your content and your responsibility",
  "3. Поділись QR": "3. Share the QR",
  "3. Хто ще має доступ": "3. Who else has access",
  "30 днів": "30 days",
  "4. Поширення посилань": "4. Sharing links",
  "4. Скільки зберігаємо": "4. How long we keep it",
  "5 серпня 2026": "5 August 2026",
  "5. Ваші права": "5. Your rights",
  "5. Доступність сервісу": "5. Service availability",
  "6. Безпека": "6. Security",
  "6. Резервні копії": "6. Backups",
  "7 днів": "7 days",
  "7. Діти": "7. Children",
  "7. Обмеження відповідальності": "7. Limitation of liability",
  "8. Зміни": "8. Changes",
  "8. Припинення": "8. Termination",
  "9. Зміни умов": "9. Changes to the terms",
  "9. Контакти": "9. Contacts",
  "або вставте посилання / токен": "or paste a link / token",
  "Авторизація": "Signing in",
  "Авторизація займає довше, ніж зазвичай.\nПеревірте підключення до інтернету.": "Signing in is taking longer than usual.\nCheck your internet connection.",
  "Адреса": "Address",
  "Адреса бази": "Database address",
  "Акаунт видалено": "Account deleted",
  "акаунт створюється автоматично через ваш Telegram-профіль;": "the account is created automatically from your Telegram profile;",
  "Активний": "Active",
  "Активних доступів немає": "No active access",
  "Активувати старе": "Reactivate old",
  "Активувати старе посилання?": "Reactivate the old link?",
  "Аналітика бази": "Database analytics",
  "Аналітика і поширення": "Analytics and sharing",
  "Аналітика підбірки": "Collection analytics",
  "Аналітика, розрахунки — .xlsx": "Analytics, calculations — .xlsx",
  "Анонім": "Anonymous",
  "Архів": "Archive",
  "Архів порожній": "The archive is empty",
  "Баз": "Databases",
  "База": "Database",
  "База не знайдена або посилання застаріло": "Database not found or the link has expired",
  "База обʼєктів": "Unit database",
  "база розрахунку": "calculation basis",
  "База розрахунку": "Calculation basis",
  "База: {0}": "Database: {0}",
  "Бази": "Databases",
  "Бази команди не завантажились": "Team databases failed to load",
  "Базу «{0}» і {1}. Це незворотно.": "“{0}” and {1}. This cannot be undone.",
  "Базу видалено": "Database deleted",
  "Базу не знайдено": "Database not found",
  "Базу не знайдено або посилання застаріло.": "Database not found or the link has expired.",
  "Базу оновлено": "Database updated",
  "Базу підключено!": "Database connected!",
  "Базу підключено! 🎉": "Database connected! 🎉",
  "Базу створено": "Database created",
  "Без обмежень": "No expiry",
  "Без папки": "No folder",
  "Без паролів — миттєва авторизація": "No passwords — instant sign-in",
  "Безпека даних": "Data security",
  "безстрокове": "no expiry",
  "Бізнес-центр": "Business centre",
  "Більше обʼєктів": "More units",
  "Бірюзовий": "Teal",
  "Брендований PDF — зберігається та шериться": "Branded PDF — save and share",
  "Буде {0} видалено: усі бази та обʼєкти, фото й документи, платежі, підбірки й доступи. Відновити неможливо.": "This will {0} delete: all databases and units, photos and documents, payments, collections and access. It cannot be undone.",
  "Буде імпортовано": "Will be imported",
  "Буде створено": "Will be created",
  "Будинки, ділянки": "Houses, land plots",
  "будь-хто, хто має ваше активне публічне посилання (перегляд без входу) — ви можете відкликати його будь-коли;": "anyone holding your active public link (view without sign-in) — you can revoke it at any time;",
  "БЦ Олімп": "Olimp Business Centre",
  "В": "In",
  "В базу": "To database",
  "В команді": "On the team",
  "Валюта": "Currency",
  "ваш Telegram ID, імʼя, прізвище та @username (якщо він у вас є);": "your Telegram ID, first name, last name and @username (if you have one);",
  "Ваші дані бачите лише ви та ті, кому ви їх свідомо відкрили:": "Only you and those you deliberately grant access to can see your data:",
  "Введіть суму...": "Enter an amount...",
  "Вгору": "Up",
  "Ви в команді! 🎉": "You are on the team! 🎉",
  "ви відповідаєте за доступ до свого Telegram-акаунта;": "you are responsible for access to your Telegram account;",
  "Ви зобовʼязуєтесь:": "You agree to:",
  "Ви можете припинити користування будь-коли й попросити видалити акаунт (див. Політику конфіденційності). Після видалення відновити дані неможливо.": "You may stop using the service at any time and request account deletion (see the Privacy Policy). Once deleted, data cannot be recovered.",
  "Ви отримаєте повідомлення через Telegram за {0} дн. до {1}-го числа кожного місяця.": "You will get a Telegram message {0} days before the {1} of each month.",
  "Вибрати все": "Select all",
  "видалення бази": "deleting the database",
  "видалення запису доступу": "deleting the access record",
  "видалення обʼєкта": "deleting the unit",
  "видалення обʼєктів": "deleting the units",
  "видалення папки": "deleting the folder",
  "видалення підбірки": "deleting the collection",
  "видалення розкладу": "deleting the schedule",
  "видалення файлу": "deleting the file",
  "видалення фото": "deleting the photo",
  "Видалено {0} {1}": "Deleted {0} {1}",
  "Видалити": "Delete",
  "ВИДАЛИТИ": "DELETE",
  "Видалити ({0})": "Delete ({0})",
  "Видалити {0} {1}": "Delete {0} {1}",
  "Видалити {0} {1}?": "Delete {0} {1}?",
  "Видалити акаунт": "Delete account",
  "видалити акаунт і всі повʼязані дані;": "delete the account and all related data;",
  "Видалити акаунт?": "Delete account?",
  "Видалити базу": "Delete database",
  "Видалити базу?": "Delete database?",
  "Видалити з підбірки": "Remove from collection",
  "Видалити обʼєкт": "Delete unit",
  "Видалити обʼєкт?": "Delete unit?",
  "Видалити папку «{0}»?": "Delete folder “{0}”?",
  "Видалити підбірку": "Delete collection",
  "Видалити підбірку?": "Delete collection?",
  "Видалити розклад?": "Delete schedule?",
  "Видалити сповіщення": "Delete notification",
  "Видалити файл?": "Delete file?",
  "Видалити фото": "Delete photo",
  "Видалити фото?": "Delete photo?",
  "Видаліть зайві, щоб додати нові": "Delete some to add new ones",
  "Виділити обʼєкти": "Select units",
  "Виділіть і скопіюйте посилання вручну": "Select and copy the link manually",
  "Вийти": "Sign out",
  "Вийти з акаунту": "Sign out",
  "Вийти з акаунту?": "Sign out?",
  "Вимкнено — глядач бачить ваше імʼя та Telegram, але не номер. Посилання діють, доки ви їх не відкличете, тож номер, показаний раз, лишається видимим усім, хто зберіг лінк.": "Off — viewers see your name and Telegram, but not your phone number. Links stay valid until you revoke them, so a number shown once remains visible to everyone who saved the link.",
  "вимкнути сповіщення в профілі.": "turn off notifications in your profile.",
  "виправити неточні дані — більшість полів редагується просто в застосунку;": "correct inaccurate data — most fields are editable right in the app;",
  "від {0}": "from {0}",
  "від зайнятих": "from occupied",
  "Відкликані": "Revoked",
  "відкликання доступу": "revoking access",
  "Відкликано": "Revoked",
  "Відкликати": "Revoke",
  "Відкликати доступ": "Revoke access",
  "Відкликати доступ?": "Revoke access?",
  "відкликати публічні посилання, гостьовий доступ і доступ команди — у розділах поширення та команди;": "revoke public links, guest access and team access — in the sharing and team sections;",
  "Відкрийте додаток через Telegram Mini App": "Open the app through the Telegram Mini App",
  "Відкрити": "Open",
  "Відкрити в Telegram": "Open in Telegram",
  "Відкрити підбірку в Telegram": "Open the collection in Telegram",
  "Відкрити prostir": "Open prostir",
  "відкриттів": "opens",
  "відкриття": "opens",
  "Відскануй QR від власника": "Scan the owner’s QR",
  "Відскануй QR-код бази prostir": "Scan a prostir database QR code",
  "Відскануй QR-код від власника,{0}щоб отримати доступ до бази": "Scan the owner’s QR code{0}to get access to the database",
  "Відскануйте QR від prostir": "Scan a prostir QR",
  "Відскануйте QR-код": "Scan a QR code",
  "Відстежувати та відмічати оплати": "Track and mark payments",
  "Вільна площа": "Vacant area",
  "вільно": "vacant",
  "Вільно": "Vacant",
  "Вільно ({0})": "Vacant ({0})",
  "Вкажіть, яка колонка містить назву": "Specify which column holds the name",
  "Власник": "Owner",
  "Власник бази": "Database owner",
  "Власник надішле вам запрошення-посилання": "The owner will send you an invitation link",
  "Вниз": "Down",
  "Водопостачання": "Water supply",
  "Воно знову запрацює для ВСІХ, хто його вже має — включно з тими, у кого ви відкликали доступ. Щоб роздати доступ заново, скористайтесь «Оновити посилання».": "It will work again for EVERYONE who already has it — including those whose access you revoked. To hand out access afresh, use “Refresh link”.",
  "Впишіть": "Type",
  "Всі": "All",
  "Всі ({0})": "All ({0})",
  "всі {0} {1} буде видалено": "all {0} {1} will be deleted",
  "Всі вибрані обʼєкти і їхні фото будуть видалені. Це незворотно.": "All selected units and their photos will be deleted. This cannot be undone.",
  "Всі платежі за цей місяць підтверджено": "All payments for this month are confirmed",
  "Всі розклади налаштовано — тут зʼявляться майбутні платежі": "All schedules are set — upcoming payments will appear here",
  "Всі{0}": "All{0}",
  "Встановіть орендарів для відстеження платежів": "Set tenants to track payments",
  "ВСЬОГО": "TOTAL",
  "Всього отримано за весь час": "Total received all time",
  "Вся корисна площа": "All usable area",
  "Вт": "Tue",
  "вул. Хрещатик, 1": "1 Khreshchatyk St",
  "Вхід через Telegram": "Sign in with Telegram",
  "вчора": "yesterday",
  "Вчора": "Yesterday",
  "Газопостачання": "Gas supply",
  "Гість": "Guest",
  "Гість «{0}» втратить доступ. Цю дію не можна скасувати.": "Guest “{0}” will lose access. This action cannot be undone.",
  "Гості": "Guests",
  "Гості бази": "Database guests",
  "Гості обʼєкта": "Unit guests",
  "гості, яким ви видали гостьовий доступ.": "guests to whom you granted guest access.",
  "Гостьовий доступ": "Guest access",
  "Готівка, переказ, часткова оплата...": "Cash, transfer, partial payment...",
  "Готово": "Done",
  "Групуйте обʼєкти бази": "Group the units in a database",
  "Дані зберігаються, доки існує ваш акаунт. Коли ви видаляєте обʼєкт, базу чи фотографію — вони видаляються разом із повʼязаними файлами. Службові журнали й записи обмеження частоти запитів зберігаються короткий час і очищаються автоматично.": "Data is kept for as long as your account exists. When you delete a unit, a database or a photo, it is deleted together with the related files. Service logs and rate-limit records are kept briefly and cleared automatically.",
  "Дані передаються лише через HTTPS. Доступ до рядків у базі обмежений політиками рівня рядків: запит від одного користувача технічно не може прочитати чужі дані. Дані входу з Telegram перевіряються криптографічним підписом на сервері.": "Data is transmitted over HTTPS only. Access to rows in the database is restricted by row-level security policies: one user’s query technically cannot read another user’s data. Telegram sign-in data is verified by a cryptographic signature on the server.",
  "дані про обʼєкти: назви, адреси, площі, поверхи, ставки оренди та експлуатації, описи;": "unit data: names, addresses, areas, floors, rent and service-charge rates, descriptions;",
  "Дані третіх осіб, які вводите ви:": "Third-party data that you enter:",
  "Дані Telegram": "Telegram data",
  "Дата закінчення оренди раніше початку": "The lease end date is earlier than the start",
  "Дата: {0}": "Date: {0}",
  "день": "day",
  "День місяця": "Day of month",
  "День місяця (1–28)": "Day of month (1–28)",
  "День платежу має бути від 1 до 28": "The payment day must be between 1 and 28",
  "Діагностика підключення": "Connection diagnostics",
  "Дії з базою": "Database actions",
  "Дії з обʼєктом": "Unit actions",
  "Дії з обʼєктом «{0}»": "Actions for “{0}”",
  "Ділись QR з ріелторами": "Share the QR with agents",
  "Для імпорту назад у застосунок": "For importing back into the app",
  "Для клієнтів": "For clients",
  "Для повторного входу знадобиться Telegram.": "You will need Telegram to sign in again.",
  "дні": "days",
  "днів": "days",
  "до {0}": "until {0}",
  "Добрий вечір": "Good evening",
  "Добрий день": "Good afternoon",
  "Доброго ранку": "Good morning",
  "добу": "day",
  "Договір": "Lease",
  "Договір від": "Lease from",
  "Договір до": "Lease until",
  "Договір з": "Lease from",
  "Договір закінчився {0} {1} тому": "The lease ended {0} {1} ago",
  "Договір закінчується сьогодні": "The lease ends today",
  "Договір оренди": "Lease agreement",
  "Договори{0}": "Leases{0}",
  "додав до обраних": "added to favourites",
  "Додай перший обʼєкт до підбірки": "Add the first unit to the collection",
  "Додайте обʼєкти перед тим як ділитися": "Add units before sharing",
  "Додайте перший обʼєкт": "Add the first unit",
  "Додайте PDF або Word файли (до {0} шт., макс. 20 МБ) — або перетягніть їх сюди": "Add PDF or Word files (up to {0}, max 20 MB) — or drag them here",
  "Додано": "Added",
  "Додано {0} {1}": "Added {0} {1}",
  "Додати": "Add",
  "Додати {0} {1}": "Add {0} {1}",
  "Додати базу за QR": "Add a database by QR",
  "Додати до підбірки": "Add to collection",
  "Додати документ": "Add document",
  "Додати обʼєкт": "Add unit",
  "Додати папку": "Add folder",
  "Додати перший обʼєкт": "Add the first unit",
  "Додати фото": "Add photo",
  "Додати ще файл": "Add another file",
  "Додатковий опис обʼєкту...": "Additional description of the unit...",
  "Додаткові контакти": "Additional contacts",
  "Дозволені лише зображення (JPG, PNG, WEBP, HEIC)": "Images only (JPG, PNG, WEBP, HEIC)",
  "Документ прибрано зі списку, але файл лишився у сховищі": "The document was removed from the list, but the file remains in storage",
  "доступ": "access",
  "Доступ": "Access",
  "Доступ відкликано": "Access revoked",
  "Доступ до документів та файлів": "Access to documents and files",
  "Доступ отримано! 🎉": "Access granted! 🎉",
  "доступи": "access records",
  "Доступи": "Access",
  "доступів": "access records",
  "Доступів": "Access records",
  "Досягнуто ліміту {0} файлів": "Limit of {0} files reached",
  "Дублювати": "Duplicate",
  "Експл.": "Serv.",
  "експлуатаційні": "service charges",
  "Експлуатаційні": "Service charges",
  "Експлуатаційні / міс": "Service charges / mo",
  "Експлуатаційні на місяць": "Service charges per month",
  "Експлуатаційні на місяць ({0})": "Service charges per month ({0})",
  "Експлуатаційні послуги": "Service charges",
  "ЕКСПЛУАТАЦІЙНІ ПОСЛУГИ": "SERVICE CHARGES",
  "Експорт": "Export",
  "Експорт недоступний офлайн": "Export is unavailable offline",
  "Електропостачання": "Electricity",
  "Є": "Yes",
  "Є паркінг": "Parking available",
  "Житловий комплекс": "Residential complex",
  "ЖК": "RC",
  "З Telegram (автоматично, під час входу):": "From Telegram (automatically, at sign-in):",
  "за": "in",
  "за 7 днів": "in 7 days",
  "За добу": "Per day",
  "за м²": "per m²",
  "За м²": "Per m²",
  "За місяць": "Per month",
  "За орендою": "By rent",
  "За площею": "By area",
  "За поверхом": "By floor",
  "За порядком": "By order",
  "Забагато спроб входу. Зачекайте хвилину і спробуйте ще раз.": "Too many sign-in attempts. Wait a minute and try again.",
  "Завантаження": "Loading",
  "Завантаження триває довше, ніж зазвичай...": "Loading is taking longer than usual...",
  "Завантаження фото": "Uploading photos",
  "Завантаження фото недоступне офлайн": "Photo upload is unavailable offline",
  "Завантаження...": "Loading...",
  "Завантажено {0} з {1}": "Uploaded {0} of {1}",
  "Завантажено лише {0}": "Only {0} uploaded",
  "Завантажено!": "Uploaded!",
  "завантажив документ": "uploaded a document",
  "Завантажити": "Download",
  "Завантажити файл": "Upload file",
  "Завантажити фото": "Upload photo",
  "Завантажити CSV": "Download CSV",
  "Завантажити Excel": "Download Excel",
  "Завантажити PDF": "Download PDF",
  "Завантажуємо профіль...": "Loading your profile...",
  "Завантажуємо...": "Loading...",
  "Завеликі: {0} — максимум {1} МБ": "Too large: {0} — max {1} MB",
  "Завершено": "Completed",
  "Завтра": "Tomorrow",
  "заг: {0} м²": "billable: {0} m²",
  "Зайнятість": "Occupancy",
  "Зайнято": "Occupied",
  "Зайнято ({0})": "Occupied ({0})",
  "закінчився": "ended",
  "Закрити": "Close",
  "Залишилось {0} {1}": "{0} {1} left",
  "Запис про «{0}» зникне зі списку. Доступ уже відкликано, тож на права це не впливає.": "The record for “{0}” will disappear from the list. Access is already revoked, so this does not affect permissions.",
  "Запросити в команду": "Invite to team",
  "Запросити гостя": "Invite a guest",
  "Запрошення": "Invitation",
  "Запрошення відкликано власником": "The invitation was revoked by the owner",
  "Запрошення до команди бази нерухомості": "Invitation to a property database team",
  "Запрошення до перегляду": "Invitation to view",
  "Запрошення до перегляду бази": "Invitation to view a database",
  "Запрошення до перегляду обʼєкта": "Invitation to view a unit",
  "Запрошення не знайдено або відкликано": "The invitation was not found or has been revoked",
  "Запрошення не знайдено або недійсне": "The invitation was not found or is invalid",
  "Запрошення створено!": "Invitation created!",
  "Запрошення та керування доступом": "Invitations and access management",
  "Зарядка для електромобіля": "EV charging",
  "Зарядка EV": "EV charging",
  "Застарілий тригер handle_new_user блокує реєстрацію. Запустіть 003_reconcile.sql у Supabase → SQL Editor.": "A stale handle_new_user trigger is blocking sign-up. Run 003_reconcile.sql in Supabase → SQL Editor.",
  "Зателефонувати": "Call",
  "Зберегти": "Save",
  "Зберегти зміни": "Save changes",
  "Збереження недоступне офлайн": "Saving is unavailable offline",
  "Збережено": "Saved",
  "Зберігай обрані обʼєкти": "Keep your favourite units",
  "збій": "error",
  "Зведена": "Summary",
  "Зведена таблиця": "Summary table",
  "Звільнити обʼєкт": "Mark as vacant",
  "Згенеруємо запрошення-посилання": "We will generate an invitation link",
  "Здати в оренду": "Let out",
  "Зелений": "Green",
  "Зміни недоступні офлайн": "Changes are unavailable offline",
  "Змінити порядок": "Reorder",
  "Змінні та БД налаштовані. Якщо вхід не працює — перевірте правильність TELEGRAM_BOT_TOKEN.": "Environment variables and the database are configured. If sign-in does not work, check that TELEGRAM_BOT_TOKEN is correct.",
  "зміну порядку": "reordering",
  "зміну статусу": "the status change",
  "знайдено": "found",
  "Значення не може бути відʼємним": "The value cannot be negative",
  "Зняти все": "Clear all",
  "Зрозуміло": "Got it",
  "Зʼєднання відновлено": "Connection restored",
  "зʼєднання з БД": "database connection",
  "Імпорт із CSV": "Import from CSV",
  "Імпортувати": "Import",
  "Імʼя": "Name",
  "Імʼя повторюється": "The name is duplicated",
  "Індивідуальний обʼєкт": "Individual unit",
  "Інший файл": "Another file",
  "Інших баз ще немає. Введіть назву вгорі — обрані обʼєкти переїдуть у нову.": "There are no other databases yet. Enter a name above and the selected units will move into the new one.",
  "Календар платежів": "Payment calendar",
  "Картки": "Cards",
  "Квартири, пентхауси": "Flats, penthouses",
  "Кількість": "Quantity",
  "Кількість місць": "Number of spaces",
  "Класик": "Classic",
  "Код запрошення": "Invitation code",
  "код мови інтерфейсу.": "the interface language code.",
  "Колір мітки": "Label colour",
  "Колонка {0}": "Column {0}",
  "Колонки": "Columns",
  "Команда": "Team",
  "Команда бази": "Database team",
  "Команди поки немає": "No team yet",
  "Компактно": "Compact",
  "Контакти": "Contacts",
  "Контакти власника": "Owner contacts",
  "Контакти власника:": "Owner contacts:",
  "контакти для звʼязку — email і телефон (необовʼязково);": "contact details — email and phone (optional);",
  "Контакти не вказані": "No contacts provided",
  "Конфігурація OK": "Configuration OK",
  "Конфіденційність": "Privacy",
  "корисна": "usable",
  "Корисна": "Usable",
  "Корисна площа": "Usable area",
  "Корисна площа — лише число": "Usable area must be a number",
  "Корисна площа більша за розрахункову": "Usable area is larger than billable area",
  "Корисна площа обʼєкта {0}": "Usable area of unit {0}",
  "Корисна площа, м²": "Usable area, m²",
  "Корисної": "Usable",
  "Користуючись prostir, ви погоджуєтесь із цими умовами. Якщо ви не згодні — не користуйтесь сервісом.": "By using prostir you agree to these terms. If you do not agree, do not use the service.",
  "Критий": "Covered",
  "Крок 1 з 2": "Step 1 of 2",
  "Крок 2 з 2": "Step 2 of 2",
  "Куди імпортувати колонку «{0}»": "Where to import column “{0}”",
  "лічильник відкриттів ваших публічних посилань (без ідентифікації відвідувача);": "a counter of opens of your public links (without identifying the visitor);",
  "Логістика": "Logistics",
  "Людина отримає право редагувати обʼєкти цієї бази": "This person will be able to edit the units in this database",
  "м.": "c.",
  "м²": "m²",
  "Магазини, бутики": "Shops, boutiques",
  "Максимум {0} МБ — розділіть його на частини": "Maximum {0} MB — split it into parts",
  "Максимум {0} обʼєктів за раз": "Maximum {0} units at a time",
  "Максимум {0} файлів на обʼєкт": "Maximum {0} files per unit",
  "Максимум {0} фото на обʼєкт": "Max {0} photos per property",
  "мати право вносити дані, які вносите, — зокрема дані орендарів та третіх осіб;": "have the right to enter the data you enter — in particular tenant and third-party data;",
  "Менше обʼєктів": "Fewer units",
  "Меню бази": "Database menu",
  "Ми {0} продаємо ваші дані, не передаємо їх рекламним мережам і не використовуємо для профілювання чи реклами.": "We do {0} sell your data, do not share it with ad networks and do not use it for profiling or advertising.",
  "Ми можемо оновлювати ці умови. Дата вгорі показує останню редакцію; суттєві зміни анонсуємо в застосунку.": "We may update these terms. The date above shows the latest revision; we announce material changes in the app.",
  "Ми можемо призупинити акаунт, який порушує ці правила або шкодить іншим користувачам.": "We may suspend an account that breaks these rules or harms other users.",
  "Ми намагаємось тримати сервіс доступним, але не гарантуємо безперервної роботи: можливі технічні перерви, оновлення та збої на боці Telegram чи наших підрядників. Сервіс надається «як є».": "We try to keep the service available but do not guarantee uninterrupted operation: technical breaks, updates and failures on the side of Telegram or our contractors are possible. The service is provided “as is”.",
  "Ми робимо технічні резервні копії, але це не замінює ваших власних копій важливих документів. Для критичних даних тримайте окремий архів — у застосунку є експорт.": "We make technical backups, but this does not replace your own copies of important documents. Keep a separate archive of critical data — the app has an export function.",
  "міс": "mo",
  "місце": "space",
  "Місце": "Space",
  "місць": "spaces",
  "Місць": "Spaces",
  "Місць паркінгу": "Parking spaces",
  "місця": "spaces",
  "Мова": "Language",
  "Модерн": "Modern",
  "Можливо, її видалили, або в тебе більше немає до неї доступу.": "It may have been deleted, or you no longer have access to it.",
  "Можливо, його видалили.": "It may have been deleted.",
  "Мої бази": "My databases",
  "Мої обʼєкти": "My units",
  "Мої підбірки": "My collections",
  "На місяць": "Per month",
  "Нагадати за, днів": "Remind me, days before",
  "Нагадування про строки оплати": "Payment due reminders",
  "надає вам доступ до:": "gives you access to:",
  "Надіслати посилання": "Send link",
  "Надішли підбірку клієнту — тут буде видно, коли він її відкрив": "Send the collection to a client — you will see here when they opened it",
  "Надішліть гостю для отримання доступу": "Send this to the guest to grant access",
  "Надішліть майбутньому члену команди": "Send this to the future team member",
  "НАЗАВЖДИ": "PERMANENTLY",
  "Назад": "Back",
  "Назва": "Name",
  "Назва бази": "Database name",
  "Назва нової бази": "New database name",
  "Назва нової бази…": "New database name…",
  "Назва нової папки": "New folder name",
  "Назва обʼєкта": "Unit name",
  "Назва обʼєкта {0}": "Name of unit {0}",
  "Назва папки…": "Folder name…",
  "Найближчі платежі": "Upcoming payments",
  "Найменування": "Name",
  "Налаштовуємо середовище...": "Setting up the environment...",
  "Налаштування": "Settings",
  "налаштування: валюта, сповіщення.": "settings: currency, notifications.",
  "Налаштувати": "Set up",
  "Налаштувати розклад": "Set up schedule",
  "Написати власнику": "Message the owner",
  "Написати нам": "Message us",
  "напр. Менеджер Оля": "e.g. Manager Olha",
  "напр. Орендар, кв. 5": "e.g. Tenant, flat 5",
  "Направте камеру на QR-код від власника бази": "Point the camera at the QR code from the database owner",
  "Наприклад \"БЦ Олімп\" або \"ЖК Перемоги\"": "For example “Olimp Business Centre” or “Peremohy Residential Complex”",
  "Наступне фото": "Next photo",
  "Натискаючи «Увійти», ви погоджуєтесь з {0} та {1}": "By tapping “Sign in” you agree to the {0} and the {1}",
  "Натисни + щоб додати перший обʼєкт": "Tap + to add the first unit",
  "Натисніть «Оновити посилання», щоб створити нове": "Tap “Refresh link” to create a new one",
  "Натисніть ↑ або ↓ щоб змінити позицію обʼєкта": "Tap ↑ or ↓ to change the unit’s position",
  "Натисніть + щоб запросити гостя": "Tap + to invite a guest",
  "Натисніть + щоб запросити помічника": "Tap + to invite an assistant",
  "Натисніть +, щоб внести квартиру, офіс або приміщення з площею, статусом та орендою.": "Tap + to add a flat, office or space with its area, status and rent.",
  "Натисніть +, щоб додати базу нерухомості — офісний центр, житловий комплекс або склад.": "Tap + to add a property database — an office centre, a residential complex or a warehouse.",
  "Натисніть +, щоб зібрати підбірку обʼєктів для клієнта та поділитися посиланням.": "Tap + to build a collection of units for a client and share a link.",
  "Наявність": "Availability",
  "Нд": "Sun",
  "не": "not",
  "Не вдалося видалити акаунт": "Could not delete the account",
  "Не вдалося видалити фото": "Could not delete the photo",
  "Не вдалося відкрити файл": "Could not open the file",
  "Не вдалося завантажити": "Could not load",
  "Не вдалося завантажити архів": "Could not load the archive",
  "Не вдалося завантажити бази": "Could not load the databases",
  "Не вдалося завантажити дані": "Could not load the data",
  "Не вдалося завантажити дані. Перевірте підключення.": "Could not load the data. Check your connection.",
  "Не вдалося завантажити документи": "Could not load the documents",
  "Не вдалося завантажити обʼєкт": "Could not load the unit",
  "Не вдалося завантажити шрифт для PDF": "Could not load the font for the PDF",
  "Не вдалося завантажити. Перевір зʼєднання та спробуй ще раз.": "Could not load. Check your connection and try again.",
  "Не вдалося зберегти порядок": "Could not save the order",
  "Не вдалося здати в оренду": "Could not let the unit",
  "Не вдалося змінити посилання": "Could not change the link",
  "Не вдалося оновити платежі": "Could not update the payments",
  "Не вдалося перевірити посилання": "Could not verify the link",
  "Не вдалося перемістити": "Could not move",
  "Не вдалося перенести": "Could not transfer",
  "Не вдалося підтвердити право власності на обʼєкт": "Could not confirm ownership of the unit",
  "Не вдалося скопіювати": "Could not copy",
  "Не вдалося створити": "Could not create",
  "не використовувати сервіс для розсилки спаму чи введення людей в оману;": "not use the service to send spam or mislead people;",
  "Не вказано": "Not specified",
  "Не вказано базу": "No database specified",
  "не завантажувати незаконний, шахрайський чи чужий захищений контент;": "not upload unlawful, fraudulent or someone else’s protected content;",
  "Не закривайте додаток": "Do not close the app",
  "Не збереглося — повернуто як було": "Not saved — reverted to the previous state",
  "Не зображення: {0}": "Not images: {0}",
  "Не можна прийняти власне запрошення": "You cannot accept your own invitation",
  "Не налаштовано в Supabase → Edge Functions → Secrets: {0}": "Not configured in Supabase → Edge Functions → Secrets: {0}",
  "не намагатись обійти обмеження доступу, ламати чи перевантажувати сервіс.": "not attempt to bypass access restrictions, break or overload the service.",
  "Не підійшов жоден файл": "No file was suitable",
  "Невідома помилка": "Unknown error",
  "Невірний email": "Invalid email",
  "Невірний QR-код": "Invalid QR code",
  "Недійсне посилання": "Invalid link",
  "Незбережений обʼєкт з минулого разу": "An unsaved unit from last time",
  "Некоректне значення": "Invalid value",
  "Некоректні дані. Перевірте введене й спробуйте ще раз.": "Invalid data. Check what you entered and try again.",
  "Немає": "None",
  "Немає баз": "No databases",
  "Немає баз за запитом": "No databases match the query",
  "Немає баз за запитом \"": "No databases match “",
  "Немає відповіді від сервера. Перевірте інтернет.": "No response from the server. Check your internet connection.",
  "Немає вільних обʼєктів": "No vacant units",
  "Немає доступних обʼєктів": "No available units",
  "Немає доступу до цих даних.": "You do not have access to this data.",
  "Немає доступу: {0}": "No access: {0}",
  "Немає жодної бази": "No databases yet",
  "Немає зайнятих обʼєктів": "No occupied units",
  "Немає запрошень": "No invitations",
  "Немає зʼєднання з інтернетом. Перевір мережу і спробуй ще раз.": "No internet connection. Check your network and try again.",
  "Немає зʼєднання з інтернетом. Перевірте мережу і спробуйте ще раз.": "No internet connection. Check your network and try again.",
  "Немає зʼєднання з сервером. Перевірте інтернет.": "No connection to the server. Check your internet.",
  "Немає зʼєднання. Перевірте інтернет і спробуйте ще раз.": "No connection. Check your internet and try again.",
  "Немає інтернету": "No internet",
  "Немає інтернету — дані можуть бути застарілими": "No internet — the data may be out of date",
  "Немає обʼєктів": "No units",
  "Немає обʼєктів для експорту": "No units to export",
  "Немає обʼєктів на продаж": "No units for sale",
  "Немає орендованих обʼєктів": "No let units",
  "Немає переглядів": "No views",
  "Немає підбірок": "No collections",
  "Немає підписок": "No subscriptions",
  "Немає результатів для \"": "No results for “",
  "Немає розкладу": "No schedule",
  "Немає сповіщень": "No notifications",
  "Необовʼязково — для сповіщень і звітів": "Optional — for notifications and reports",
  "Ні": "No",
  "Нічний": "Night",
  "Нічого не знайдено": "Nothing found",
  "Нова": "New",
  "Нова база": "New database",
  "Нова назва папки «{0}»": "New name for folder “{0}”",
  "Новий обʼєкт": "New unit",
  "нових": "new",
  "Нові перегляди": "New views",
  "Номер місця": "Space number",
  "Нотатка (необовʼязково)": "Note (optional)",
  "Нотатка до платежу": "Payment note",
  "об.": "un.",
  "Обери роль — це визначить набір функцій": "Choose a role — it determines the available features",
  "Оберіть обʼєкт із підписаних баз": "Choose a unit from your subscribed databases",
  "Оберіть обʼєкти для дії": "Select units to act on",
  "Оберіть папку або створіть нову": "Choose a folder or create a new one",
  "Обовʼязкова лише «Назва». Обʼєкти з назвами, які вже є в базі, буде пропущено.": "Only “Name” is required. Units whose names already exist in the database will be skipped.",
  "обрано": "selected",
  "Обрати файл": "Choose file",
  "обʼєкт": "unit",
  "Обʼєкт": "Unit",
  "Обʼєкт \"{0}\" буде видалено. Це незворотно.": "Unit “{0}” will be deleted. This cannot be undone.",
  "Обʼєкт {0} з {1}": "Unit {0} of {1}",
  "Обʼєкт видалено": "Unit deleted",
  "Обʼєкт додано": "Unit added",
  "Обʼєкт звільнено": "Unit marked vacant",
  "Обʼєкт здано в оренду": "Unit let",
  "Обʼєкт із такою назвою вже є в базі": "A property with this name already exists",
  "Обʼєкт не знайдено": "Unit not found",
  "Обʼєкт не знайдено або посилання застаріло.": "Unit not found or the link has expired.",
  "обʼєкти": "units",
  "Обʼєкти": "Units",
  "Обʼєкти по всіх базах": "Units across all databases",
  "обʼєктів": "units",
  "Обʼєктів": "Units",
  "Обʼєктів поки немає": "No units yet",
  "обʼєктів у базі": "units in the database",
  "Обʼєктів: {0}": "Units: {0}",
  "один Telegram-акаунт — один акаунт у сервісі.": "one Telegram account — one account in the service.",
  "Оновити": "Refresh",
  "Оновити посилання": "Refresh link",
  "Оновити посилання?": "Refresh the link?",
  "Оновлено:": "Updated:",
  "Опис": "Description",
  "ОПИС": "DESCRIPTION",
  "Опис обʼєкта": "Unit description",
  "Оплата сьогодні": "Payment due today",
  "оренда": "rent",
  "Оренда": "Rent",
  "ОРЕНДА": "RENT",
  "Оренда · зайнято": "Rent · occupied",
  "Оренда / міс": "Rent / mo",
  "оренда + експлуатаційні": "rent + service charges",
  "Оренда на місяць": "Rent per month",
  "Оренда на місяць ({0})": "Rent per month ({0})",
  "Орендар": "Tenant",
  "ОРЕНДАР": "TENANT",
  "Орендна ставка": "Rent rate",
  "Орендна ставка — лише число": "The rent rate must be a number",
  "Орендна ставка за м²": "Rent rate per m²",
  "Орендодавець": "Landlord",
  "Орендодавець бази": "Database landlord",
  "Орендодавець:": "Landlord:",
  "Орендодавець: {0}": "Landlord: {0}",
  "Основне": "General",
  "Останні 7 днів": "Last 7 days",
  "Останні перегляди": "Recent views",
  "Отримано": "Received",
  "отримати копію своїх даних;": "obtain a copy of your data;",
  "Офіс 101": "Office 101",
  "Офіси з нумерацією": "Numbered offices",
  "Офіси, квартири, магазини з фото і ціною": "Offices, flats and shops with photos and prices",
  "Очистити": "Clear",
  "Очистити всі": "Clear all",
  "Очистити пошук": "Clear search",
  "Очистити сповіщення?": "Clear notifications?",
  "очищення сповіщень": "clearing notifications",
  "Очікує": "Pending",
  "Очікується": "Upcoming",
  "Очікуються": "Upcoming",
  "Папка": "Folder",
  "Папки": "Folders",
  "Папку видалено": "Folder deleted",
  "Папку створено": "Folder created",
  "Параметри перегляду не вказані. Перевірте посилання.": "No view parameters were provided. Check the link.",
  "Паркінг": "Parking",
  "ПАРКІНГ": "PARKING",
  "Паркінг:": "Parking:",
  "Паркомісце": "Parking space",
  "Паркувальні місця": "Parking spaces",
  "Перевір підключення і спробуй ще раз": "Check your connection and try again",
  "Перевірка...": "Checking...",
  "Перевірте зʼєднання — наявне посилання ЦІЛЕ, ми його просто не прочитали.": "Check your connection — the existing link is INTACT, we simply could not read it.",
  "Перевірте зʼєднання та спробуйте ще раз.": "Check your connection and try again.",
  "Перевірте налаштування Vercel": "Check your Vercel settings",
  "Перевірте формат адреси": "Check the address format",
  "Перевірте, що функцію задеплоєно у Supabase": "Check that the function is deployed in Supabase",
  "Перевіряємо дані...": "Verifying your data...",
  "Перевіряємо сесію...": "Checking your session...",
  "Перегляд бази": "Database view",
  "Перегляд усієї інформації про обʼєкт": "View all information about a unit",
  "Переглядай аналітику": "Track analytics",
  "Перегляди": "Views",
  "Переглядів за 7 днів": "Views in 7 days",
  "переглянув": "viewed",
  "переглянув фото": "viewed a photo",
  "Перегляньте базу «{0}»": "View the database “{0}”",
  "Перегляньте базу нерухомості": "View a property database",
  "Перегляньте підбірку обʼєктів": "View a collection of units",
  "Перегляньте цей обʼєкт нерухомості": "View this property unit",
  "Перезапустити": "Restart",
  "перейменування папки": "renaming the folder",
  "Перейменувати": "Rename",
  "Перемістити {0} {1}": "Move {0} {1}",
  "переміщення в папку": "moving to a folder",
  "перенесення в іншу базу": "transferring to another database",
  "Перенести в базу": "Move to database",
  "Перетягніть файл .csv": "Drag a .csv file here",
  "Перетягніть JPG, PNG або WebP": "Drag JPG, PNG or WebP here",
  "Перетягніть PDF або Word": "Drag PDF or Word here",
  "Перший рядок — заголовки колонок. Якщо файл вивантажено з цього застосунку, колонки зіставляться самі. Файл можна перетягнути сюди.": "The first row holds the column headers. If the file was exported from this app, the columns will map themselves. You can drag the file here.",
  "Перший:": "First:",
  "Питання щодо даних, запит на видалення чи копію — напишіть на {0} або через бота підтримки в Telegram.": "For data questions, deletion or copy requests — write to {0} or through the support bot in Telegram.",
  "Питання щодо умов —": "Questions about the terms —",
  "Підбірка": "Collection",
  "Підбірка {0}": "Collection {0}",
  "Підбірка порожня": "The collection is empty",
  "Підбірки": "Collections",
  "Підбірку \"{0}\" буде видалено. Це незворотно.": "Collection “{0}” will be deleted. This cannot be undone.",
  "Підбірку видалено": "Collection deleted",
  "Підбірку не знайдено": "Collection not found",
  "Підбірку не знайдено або посилання застаріло.": "Collection not found or the link has expired.",
  "Підбірку створено": "Collection created",
  "Підземний": "Underground",
  "Підключаємось до Telegram...": "Connecting to Telegram...",
  "Підключення до бази недоступне офлайн": "Connecting to a database is unavailable offline",
  "Підключення...": "Connecting...",
  "Підключити базу в Telegram": "Connect the database in Telegram",
  "Підключити базу та зареєструватись": "Connect the database and sign up",
  "Підключіться до бази": "Connect to a database",
  "Підпис (необовʼязково)": "Label (optional)",
  "Підпис гостьового лінка": "Guest link label",
  "Підпис інвайта": "Invitation label",
  "Підписуйся на бази власників": "Subscribe to owners’ databases",
  "Підтверджені платежі зʼявляться тут": "Confirmed payments will appear here",
  "Підтвердження видалення": "Deletion confirmation",
  "Підтвердити": "Confirm",
  "Підтвердити платіж": "Confirm payment",
  "Підтримка": "Support",
  "Платежі": "Payments",
  "Платежі — {0}": "Payments — {0}",
  "Платежі{0}": "Payments{0}",
  "Платежів немає": "No payments",
  "Платіж": "Payment",
  "Платіж не зберігся": "The payment was not saved",
  "Платіж підтверджено": "Payment confirmed",
  "Платіж скасовано": "Payment cancelled",
  "платформа нерухомості": "property platform",
  "Платформа управління нерухомістю в Telegram": "A property management platform in Telegram",
  "Площа": "Area",
  "Площа зайнятих": "Occupied area",
  "ПЛОЩА І РОЗТАШУВАННЯ": "AREA AND LOCATION",
  "Площа корисна": "Usable area",
  "Площа корисна (м²)": "Usable area (m²)",
  "Площа місця": "Space area",
  "Площа розрахункова": "Billable area",
  "Площа розрахункова (м²)": "Billable area (m²)",
  "Пн": "Mon",
  "Пов.": "Fl.",
  "Поверх": "Floor",
  "Повільне зʼєднання": "Slow connection",
  "поділився посиланням": "shared a link",
  "Поділись посиланням, щоб рієлтори побачили обʼєкти": "Share the link so agents can see the units",
  "Поділитись": "Share",
  "Поділитись базою": "Share database",
  "Поділитись обʼєктом": "Share unit",
  "Поділитись підбіркою": "Share collection",
  "Поділитись фото": "Share photo",
  "Поділитися": "Share",
  "Подобова оплата": "Daily rate",
  "подобово": "per day",
  "Подобово": "Per day",
  "Показати всі": "Show all",
  "Показати:": "Show:",
  "Показувати телефон на публічних сторінках": "Show phone number on public pages",
  "Політика конфіденційності": "Privacy Policy",
  "Політика конфіденційності — prostir": "Privacy Policy — prostir",
  "Політикою конфіденційності": "Privacy Policy",
  "Помаранчевий": "Orange",
  "Помилка": "Error",
  "Помилка видалення": "Deletion error",
  "Помилка видалення фото": "Photo deletion error",
  "Помилка входу": "Sign-in error",
  "Помилка доступу": "Access error",
  "Помилка експорту": "Export error",
  "Помилка завантаження": "Loading error",
  "Помилка завантаження папок": "Error loading folders",
  "Помилка запиту": "Request error",
  "Помилка збереження": "Saving error",
  "Помилка перевірки даних Telegram. Перезапустіть додаток.": "Telegram data verification failed. Restart the app.",
  "Помилка підписки": "Subscription error",
  "Помилка сервера авторизації. Перевірте налаштування Edge Function у Supabase.": "Authorisation server error. Check the Edge Function settings in Supabase.",
  "Помилка сесії авторизації. Спробуйте знову або зверніться до адміністратора.": "Authorisation session error. Try again or contact the administrator.",
  "Понад межу {0} фото: {1}": "Over the {0}-photo limit: {1}",
  "Попереднє фото": "Previous photo",
  "Попередній вигляд": "Preview",
  "Попросіть власника надіслати QR-код або посилання, потім натисніть цю кнопку.": "Ask the owner to send a QR code or a link, then tap this button.",
  "Порожній файл": "Empty file",
  "Порожня папка буде видалена.": "The empty folder will be deleted.",
  "Посилання або токен": "Link or token",
  "Посилання для перегляду": "Link for viewing",
  "Посилання застаріло, видалено або відкликано. Зверніться до власника.": "The link has expired, been deleted or revoked. Contact the owner.",
  "Посилання не сформувалось: у застосунку не налаштований юзернейм бота. Запрошення вже створене — надішліть його після налаштування.": "The link could not be built: the bot username is not configured in the app. The invitation is already created — send it once that is configured.",
  "Посилання неактивне": "The link is inactive",
  "Посилання невалідне. Перевірте QR-код або URL.": "The link is not valid. Check the QR code or the URL.",
  "Посилання невірне або застаріло": "The link is wrong or has expired",
  "Посилання недійсне": "The link is invalid",
  "Посилання недійсне або обʼєкт видалено": "The link is invalid or the unit has been deleted",
  "Посилання недійсне або підбірку видалено": "The link is invalid or the collection has been deleted",
  "Посилання недійсне або підбірку ще не опубліковано": "The link is invalid or the collection has not been published yet",
  "Посилання одразу стане неактивним. Ви зможете створити нове через «Оновити посилання».": "The link will become inactive immediately. You can create a new one via “Refresh link”.",
  "Посилання оновлено": "Link refreshed",
  "Посилання скопійовано": "Link copied",
  "Посилання створено!": "Link created!",
  "Посилання ще не створено": "No link has been created yet",
  "Поточні": "Current",
  "Потрібен рядок заголовків і хоча б один обʼєкт": "A header row and at least one unit are required",
  "Потрібен CSV": "A CSV file is required",
  "Потрібен Telegram": "Telegram is required",
  "Потрібні JPG, PNG або WebP до {0} МБ": "JPG, PNG or WebP up to {0} MB are required",
  "Почати роботу →": "Get started →",
  "Пошук бази або обʼєкту...": "Search for a database or unit...",
  "Пошук бази...": "Search databases...",
  "Пошук не вдався — перевірте зʼєднання. Це НЕ означає, що обʼєкта немає.": "The search failed — check your connection. This does NOT mean the unit does not exist.",
  "Пошук обʼєкту...": "Search units...",
  "Пошук...": "Searching...",
  "Правила користування застосунком prostir.": "Rules for using the prostir app.",
  "Прибрати": "Remove",
  "Прибрати запис?": "Remove the record?",
  "Приватне": "Private",
  "Приватність": "Privacy",
  "Привіт, {0}!": "Hello, {0}!",
  "Привіт!": "Hello!",
  "Прийняти запрошення": "Accept invitation",
  "Прийнято {0}": "Accepted {0}",
  "Проблема конфігурації": "Configuration problem",
  "Продаж": "For sale",
  "ПРОДАЖ": "FOR SALE",
  "Продаж ({0})": "For sale ({0})",
  "Продовжити →": "Continue →",
  "Пропустити →": "Skip →",
  "Пропустити все": "Skip all",
  "Пропущено (назва вже є):": "Skipped (name already exists):",
  "Просто неба": "Open air",
  "Прострочено": "Overdue",
  "Прострочено {0}д": "Overdue by {0}d",
  "Прострочено на {0} {1}": "Overdue by {0} {1}",
  "Профіль": "Profile",
  "Профіль оновлено": "Profile updated",
  "Прочитано": "Read",
  "Пт": "Fri",
  "Публічне посилання відкриває сторінку обʼєкта чи бази будь-кому, хто його має, — без входу. Ви самі вирішуєте, кому його давати, і можете будь-коли оновити або відкликати його в розділі поширення. Памʼятайте: те, що вже побачили, могли зберегти.": "A public link opens the unit or database page for anyone who holds it — without signing in. You decide who to give it to, and you can refresh or revoke it at any time in the sharing section. Remember: whatever has already been seen may have been saved.",
  "Публічний перегляд": "Public view",
  "РАЗОМ": "TOTAL",
  "Разом / місяць": "Total / month",
  "Разом на місяць": "Total per month",
  "Разом на місяць ({0})": "Total per month ({0})",
  "Разом на місяць (оренда + експлуатаційні)": "Total per month (rent + service charges)",
  "Разом/міс": "Total/mo",
  "Раніше": "Earlier",
  "Рахувати від": "Calculate from",
  "Редагування": "Editing",
  "Редагування доступне. Власник бачить, які обʼєкти ви відкривали.": "Editing is available. The owner can see which units you opened.",
  "Редагувати": "Edit",
  "Редагувати базу": "Edit database",
  "Редагувати обʼєкт": "Edit unit",
  "Редагувати платіж": "Edit payment",
  "Редагувати розклад": "Edit schedule",
  "редактори, яких ви додали в команду бази;": "editors you added to the database team;",
  "Резервне живлення": "Backup power",
  "Решта не пройшла — перевірте формат і розмір": "The rest did not pass — check the format and size",
  "Рівень": "Level",
  "Рівень / поверх": "Level / floor",
  "Ріелтор": "Agent",
  "Ріелтор ще не додав обʼєктів": "The agent has not added any units yet",
  "Ріелтори отримають доступ миттєво": "Agents get access instantly",
  "Рієлтор": "Agent",
  "рієлтори, яких ви підписали на базу через посилання;": "agents you subscribed to the database via a link;",
  "Рітейл": "Retail",
  "Робочі бази": "Working databases",
  "Рожевий": "Pink",
  "Розклад видалено": "Schedule deleted",
  "Розклад збережено": "Schedule saved",
  "Розклад платежів": "Payment schedule",
  "Розклад платежів для «{0}» буде видалено.": "The payment schedule for “{0}” will be deleted.",
  "Розрах.": "Bill.",
  "Розрахунки оренди та експлуатаційних платежів — допоміжний інструмент. Перевіряйте цифри перед використанням у договорах чи звітності. Ми не відповідаємо за фінансові рішення, ухвалені на основі даних із застосунку, та за втрачену вигоду.": "Rent and service-charge calculations are a supporting tool. Check the figures before using them in contracts or reporting. We are not liable for financial decisions taken on the basis of data from the app, nor for lost profit.",
  "розрахункова": "billable",
  "Розрахункова": "Billable",
  "Розрахункова площа": "Billable area",
  "Розрахункова площа — лише число": "Billable area must be a number",
  "Розрахункова площа (м²)": "Billable area (m²)",
  "Розрахункова площа обʼєкта {0}": "Billable area of unit {0}",
  "Розрахункова площа, м²": "Billable area, m²",
  "Розрахункової": "Billable",
  "Розрахунок": "Calculation",
  "Розширені можливості у розробці": "Advanced features are in development",
  "Рядків без назви:": "Rows with no name:",
  "Сб": "Sat",
  "Сервер не відповідає (15 сек). Перевірте інтернет і спробуйте ще раз.": "The server is not responding (15 s). Check your internet and try again.",
  "Сервіс авторизації не знайдено (404). Функція не задеплоєна на Supabase.": "Authorisation service not found (404). The function is not deployed on Supabase.",
  "Сервіс призначений для дорослих користувачів і не орієнтований на осіб молодше 16 років.": "The service is intended for adult users and is not directed at persons under 16.",
  "Сервіс тимчасово недоступний. Спробуйте пізніше.": "The service is temporarily unavailable. Try again later.",
  "Сесія Telegram застаріла. Повністю закрийте додаток і відкрийте його знову з меню бота.": "Your Telegram session has expired. Close the app completely and open it again from the bot menu.",
  "Синій": "Blue",
  "Сканер QR": "QR scanner",
  "Сканувати QR": "Scan QR",
  "скасування платежу": "cancelling the payment",
  "Скасувати": "Cancel",
  "Скасувати платіж": "Cancel payment",
  "Скасувати платіж?": "Cancel the payment?",
  "Скасувати цей платіж": "Cancel this payment",
  "Склад": "Warehouse",
  "Склади": "Warehouses",
  "Скопіювати": "Copy",
  "Скопіювати посилання": "Copy link",
  "Скоро": "Soon",
  "службові журнали помилок і обмеження частоти запитів для захисту від зловживань.": "service error logs and rate-limit records to protect against abuse.",
  "Спершу додайте обʼєкти до бази": "Add units to the database first",
  "Сплачено": "Paid",
  "сповіщення": "notifications",
  "Сповіщення": "Notifications",
  "Сповіщення очищено": "Notifications cleared",
  "сповіщень": "notifications",
  "Спробувати ще раз": "Try again",
  "Спробуйте ще раз": "Try again",
  "Спробуйте ще раз пізніше — знімок може бути доступним за прямим посиланням": "Try again later — the photo may be available via a direct link",
  "Ср": "Wed",
  "Ставка": "Rate",
  "Ставка експлуатаційних": "Service charge rate",
  "Ставка експлуатаційних — лише число": "The service charge rate must be a number",
  "Ставка експлуатаційних за м²": "Service charge rate per m²",
  "Ставка оренди": "Rent rate",
  "Старе посилання більше не діє": "The old link no longer works",
  "Старе посилання та QR-код перестануть працювати. Усі, з ким ви ділились, втратять доступ.": "The old link and QR code will stop working. Everyone you shared it with will lose access.",
  "Статус": "Status",
  "Створено {0}": "Created {0}",
  "Створи першу базу обʼєктів": "Create your first unit database",
  "Створи першу базу обʼєктів нерухомості — це займе менше хвилини": "Create your first property database — it takes less than a minute",
  "Створи першу підбірку обʼєктів для клієнта": "Create your first collection of units for a client",
  "Створити": "Create",
  "Створити базу": "Create database",
  "Створити й перемістити": "Create and move",
  "Створити й перенести": "Create and transfer",
  "Створити першу базу": "Create the first database",
  "Створити підбірку": "Create collection",
  "Створити посилання": "Create link",
  "Створіть першу базу": "Create your first database",
  "Створіть підбірку": "Create a collection",
  "Створюй бази і обʼєкти": "Create databases and units",
  "Створюй підбірки для клієнтів": "Build collections for clients",
  "Стиль PDF": "PDF style",
  "Строк договору": "Lease term",
  "Сума": "Amount",
  "Сума експлуатаційних": "Service charge amount",
  "Сума оренди": "Rent amount",
  "Сума оренди ({0}/міс)": "Rent amount ({0}/mo)",
  "Сума отриманого платежу": "Amount of the payment received",
  "Сховати відкликані": "Hide revoked",
  "сьогодні": "today",
  "Сьогодні": "Today",
  "Таблиці бази даних не створені. Потрібно накотити міграції — зверніться до адміністратора (див. RELEASE_CHECKLIST.md).": "The database tables have not been created. Migrations need to be applied — contact the administrator (see RELEASE_CHECKLIST.md).",
  "Так": "Yes",
  "Така папка вже є": "That folder already exists",
  "Такий запис уже існує.": "Such a record already exists.",
  "Тариф": "Plan",
  "Твій AI-асистент для {0} у Telegram. Бази, обʼєкти, аналітика — все в одному місці.": "Your AI assistant for {0} in Telegram. Databases, units, analytics — all in one place.",
  "Телефон": "Phone",
  "Теплопостачання": "Heating",
  "Термін дії": "Expiry",
  "Терміни договорів": "Lease deadlines",
  "Технічні дані:": "Technical data:",
  "Технічні підрядники (субпроцесори), на серверах яких працює сервіс: {0} (база даних, файли, автентифікація), {1} (хостинг інтерфейсу), {2} (доставка застосунку та сповіщень). Ми не передаємо дані нікому іншому, крім випадків, прямо вимагаючих законом.": "Technical contractors (sub-processors) on whose servers the service runs: {0} (database, files, authentication), {1} (interface hosting), {2} (app and notification delivery). We do not pass data to anyone else, except where directly required by law.",
  "Тип": "Type",
  "Тип місця": "Space type",
  "Тип нерухомості": "Property type",
  "Тип ставки": "Rate type",
  "Тип: {0}": "Type: {0}",
  "Тільки вільні обʼєкти": "Vacant units only",
  "ТОВ «Назва» або ФОП": "Company name or sole trader",
  "ТОВ або ФОП": "Company or sole trader",
  "Торговий центр": "Shopping centre",
  "Три кроки до першої бази": "Three steps to your first database",
  "Тут зʼявляться перегляди, події та попередження про кінець договору": "Views, events and lease-expiry warnings will appear here",
  "У базі немає вільних обʼєктів": "The database has no vacant units",
  "У базі поки немає обʼєктів": "The database has no units yet",
  "У папку": "To folder",
  "У підбірці поки немає обʼєктів": "The collection has no units yet",
  "У файлі {0} — розділіть його на частини": "The file has {0} — split it into parts",
  "У цій базі поки немає обʼєктів": "This database has no units yet",
  "У Telegram": "In Telegram",
  "Увійти через Telegram": "Sign in with Telegram",
  "Укр": "Ukr",
  "Умовами використання": "Terms of Use",
  "Умови": "Terms",
  "Умови використання": "Terms of Use",
  "Умови використання — prostir": "Terms of Use — prostir",
  "Управління гостями": "Guest management",
  "управління нерухомістю": "property management",
  "Усе, що ви вносите — обʼєкти, фото, документи, дані орендарів — лишається вашим. Ми не претендуємо на права на цей контент і використовуємо його лише щоб показувати вам сервіс і виконувати ваші дії (наприклад, поширення за посиланням).": "Everything you enter — units, photos, documents, tenant data — remains yours. We claim no rights to this content and use it only to show you the service and carry out your actions (for example, sharing via a link).",
  "Усього в базі —": "Total in the database —",
  "Учасник": "Member",
  "Файл": "File",
  "Файл видалено": "File deleted",
  "Файл завантажено, але не збережено: {0}": "The file was uploaded but not saved: {0}",
  "Файл завеликий": "File too large",
  "Файл занадто великий (макс. {0}МБ)": "The file is too large (max {0} MB)",
  "Файл CSV": "CSV file",
  "Файл(и) завантажено": "File(s) uploaded",
  "Файли": "Files",
  "Файли ще не додані": "No files added yet",
  "Фікс. сума": "Fixed sum",
  "фіксована {0}/міс": "fixed {0}/mo",
  "Фіксована оплата": "Fixed payment",
  "Фінанси": "Finances",
  "Фіолетовий": "Purple",
  "Формат не підтримується": "Unsupported format",
  "Формат файлу": "File format",
  "фото": "photos",
  "Фото": "Photo",
  "ФОТО": "PHOTOS",
  "Фото {0} з {1}": "Photo {0} of {1}",
  "Фото буде видалено назавжди. Це незворотно.": "The photo will be deleted permanently. This cannot be undone.",
  "Фото нерухомості {0}/{1}": "Property photo {0}/{1}",
  "Фото обʼєкта {0} з {1}": "Unit photo {0} of {1}",
  "Фото прибрано, але файл лишився": "The photo was removed, but the file remains",
  "Фотографії": "Photos",
  "фотографії та документи, які ви завантажуєте;": "photos and documents that you upload;",
  "Хрещатик 22": "22 Khreshchatyk",
  "Хто і коли відкривав посилання": "Who opened the link and when",
  "Хто переглядав": "Who viewed",
  "Хто ти?": "Who are you?",
  "Це ваша база": "This is your database",
  "Це ваша власна база": "This is your own database",
  "Це запрошення вже використано": "This invitation has already been used",
  "Це запрошення відкликано власником": "This invitation was revoked by the owner",
  "Це не зображення": "This is not an image",
  "Ці дані передає сам Telegram у підписаному вигляді, коли ви відкриваєте застосунок. Ми не бачимо ваш номер телефону з Telegram, ваші чати чи контакти.": "Telegram itself passes this data in signed form when you open the app. We do not see your Telegram phone number, your chats or your contacts.",
  "Ціна продажу": "Sale price",
  "Ціна продажу — лише число": "The sale price must be a number",
  "Ціна продажу ({0})": "Sale price ({0})",
  "Цього тижня": "This week",
  "Через {0} {1}": "In {0} {1}",
  "Через {0} дн.": "In {0} days",
  "Чернетка": "Draft",
  "Чернетку відновлено": "Draft restored",
  "Члени команди можуть створювати і редагувати обʼєкти, фото, файли та платежі цієї бази. Поділитися базою, керувати гостями і командою може лише власник. Власник бачить, які обʼєкти учасник відкривав — про це варто сказати людині, коли запрошуєте.": "Team members can create and edit the units, photos, files and payments of this database. Only the owner can share the database and manage guests and the team. The owner can see which units a member opened — it is worth telling the person when you invite them.",
  "Чт": "Thu",
  "Швидкий старт": "Quick start",
  "Ще немає папок. Введіть назву вгорі й натисніть «Додати папку».": "No folders yet. Enter a name above and tap “Add folder”.",
  "Ще немає підписок": "No subscriptions yet",
  "Що ви вводите самі:": "What you enter yourself:",
  "Що ви отримаєте:": "What you get:",
  "щоб автентифікувати вас і показувати саме ваші бази обʼєктів;": "to authenticate you and show you exactly your own unit databases;",
  "Щоб видалити акаунт або отримати копію даних, напишіть нам (розділ «Контакти»). Ми виконаємо запит упродовж 30 днів.": "To delete your account or obtain a copy of your data, write to us (the “Contacts” section). We will fulfil the request within 30 days.",
  "щоб захищати сервіс від зловживань і діагностувати збої.": "to protect the service from abuse and diagnose failures.",
  "щоб надсилати вам сповіщення, якщо ви їх увімкнули;": "to send you notifications if you have enabled them;",
  "щоб працювали функції застосунку: списки, розрахунки, календар платежів, поширення;": "to make the app’s features work: lists, calculations, the payment calendar, sharing;",
  "щойно": "just now",
  "Щось пішло не так": "Something went wrong",
  "Щотижневий звіт": "Weekly report",
  "Я — Прокс": "I’m Prox",
  "Я здаю / продаю нерухомість": "I let / sell property",
  "Я працюю з клієнтами": "I work with clients",
  "Які дані збирає prostir, навіщо, де вони зберігаються і як їх видалити.": "What data prostir collects, why, where it is stored and how to delete it.",
  "Якщо ви вносите найменування орендаря та строки договору, ви обробляєте дані іншої особи чи компанії. Ви робите це як самостійний власник цих даних і відповідаєте за наявність правових підстав. Ми виступаємо технічним оператором зберігання. Не вносьте більше даних про орендарів, ніж вам потрібно для обліку.": "If you enter a tenant’s name and lease dates, you are processing another person’s or company’s data. You do so as the independent controller of that data and are responsible for having a lawful basis. We act as the technical storage operator. Do not enter more tenant data than you need for your records.",
  "Якщо політика суттєво зміниться, ми оновимо дату вгорі та повідомимо в застосунку.": "If this policy changes materially, we will update the date above and notify you in the app.",
  "CSV збережено": "CSV saved",
  "CSV таблиця": "CSV spreadsheet",
  "Edge Function не налаштована на сервері. Натисніть «⚙ Діагностика підключення» на цьому екрані, щоб дізнатись, яку саме змінну додати в Supabase → Edge Functions → Secrets.": "The Edge Function is not configured on the server. Tap “⚙ Connection diagnostics” on this screen to find out exactly which variable to add in Supabase → Edge Functions → Secrets.",
  "Edge Function недоступна": "The Edge Function is unavailable",
  "Excel збережено": "Excel saved",
  "Excel містить два аркуші: повний список обʼєктів з формулами підсумків та зведена таблиця по статусах.": "The Excel file contains two sheets: a full list of units with total formulas, and a summary table by status.",
  "Excel таблиця": "Excel spreadsheet",
  "HMAC підпис, RLS, шифрування": "HMAC signature, RLS, encryption",
  "NEXT_PUBLIC_SUPABASE_URL не вказано": "NEXT_PUBLIC_SUPABASE_URL is not set",
  "PDF документ": "PDF document",
  "PDF Документ": "PDF Document",
  "PDF збережено": "PDF saved",
  "PDF містить шапку з назвою бази, зведену статистику по статусах, таблицю обʼєктів з кольоровими статусами та підвал з контактами.": "The PDF contains a header with the database name, summary statistics by status, a table of units with colour-coded statuses, and a footer with contacts.",
  "prostir — застосунок для управління нерухомістю всередині Telegram. Ця політика пояснює, які дані ми обробляємо, навіщо і як ви можете їх видалити.": "prostir is a property management app inside Telegram. This policy explains what data we process, why, and how you can delete it.",
  "prostir — інструмент обліку нерухомості всередині Telegram: ви ведете бази обʼєктів, рахуєте оренду й експлуатаційні платежі, зберігаєте фото та документи, ділитесь добірками з рієлторами й клієнтами.": "prostir is a property record-keeping tool inside Telegram: you keep databases of units, calculate rent and service charges, store photos and documents, and share collections with agents and clients.",
  "prostir — платформа управління нерухомістю в Telegram. Бази обʼєктів, аналітика переглядів, підбірки для ріелторів.": "prostir is a property management platform in Telegram. Unit databases, view analytics, collections for agents.",
  "QR-код для ріелторів — не для власника": "The QR code is for agents — not for the owner",
  "Word документ": "Word document",
}
